### ISSUE TITLE
Avoid the old school null check

### ISSUE THREAD

**Issue by stevehine** [ianfnelson/ColourBlanketWeb#1]
https://github.com/ianfnelson/ColourBlanketWeb/blob/07133d6abf739a9f8ad369ca4735bae7fac48a85/ColourBlanketWeb/Controllers/HomeController.cs#L24

`ViewData["ColourBlanket"] = _cache.GetOrCreate(cacheKey, entry => GetTemperatures());`

**Comment by ianfnelson** [comment]
While you're here, can you figure out why it's being cached indefinitely?
http://blanket.iannelson.uk/

**Comment by stevehine** [comment]
try this:

```
ViewData["ColourBlanket"] = _cache.GetOrCreate(cacheKey, entry => 
  { 
    entry.setSlidingExpiration(new TimeSpan(0,5,0)); 
    return GetTemperatures();
  });
```

**Comment by ianfnelson** [comment]
Thank you. Fixed with this commit
https://github.com/ianfnelson/ColourBlanketWeb/commit/01755bf7333ed96ff8bc89eb56424e1249d2f899
